---
- name: Register docker images info
  shell: >-
    /usr/bin/docker images -q | xargs /usr/bin/docker inspect -f {%raw%}"{{ if .RepoTags }}{{range .RepoTags -}}{{.}},{{end}}{{end}}{{ if .RepoDigests }}{{ (index .RepoDigests 0) }}{{ end }}"{%endraw%} | tr '\n' ','
  no_log: false
  register: docker_images
  failed_when: false
  changed_when: false
  check_mode: no
  when: download_container

- name: container_download | Create dest directory for saved/loaded container images
  file:
    path: "{{local_release_dir}}/containers"
    state: directory
    recurse: yes
    mode: 0755
    owner: "{{ansible_ssh_user|default(ansible_user_id)}}"
  when: download_container

- name: container_download | create local directory for saved/loaded container images
  file:
    path: "{{local_release_dir}}/containers"
    state: directory
    recurse: yes
  delegate_to: localhost
  delegate_facts: false
  become: false
  run_once: true
  when:
    - download_run_once
    - download_delegate == 'localhost'
    - download_container
  tags:
    - localhost
